# Generated by Django 2.1.7 on 2019-03-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
